# 第3章のサンプルコード

バージョン1.10.10で動作確認しています．

事前にインストールが必要なパッケージ
+ LinearAlgebra
+ SparseArrays
+ SymPy

## 3.2節：基本変形

In [1]:
using LinearAlgebra
using SparseArrays

In [ ]:
# 基本変形 P
function P(m,i,j)
    A = spdiagm(0 => ones(m)) # diagmでもOK (spdiagmを用いるにはSparseArraysが必要)
    A[i, :], A[j, :] = A[j, :], A[i, :]
    return A
end

P(6,2,5)

In [ ]:
P(6,2,5)*P(6,2,5)

## 3.3節：階数

In [2]:
A = [1 2 2 6; 
    3 6 8 24;
    2 4 4 12]

3×4 Matrix{Int64}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [3]:
rank(A)

2

In [4]:
using SymPy
A = Sym[1 2 2 6; 
    3 6 8 24;
    2 4 4 12]
# show(stdout, "text/plain", A)

3×4 Matrix{Sym}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [5]:
A.rref()[1]

3×4 Matrix{Sym{PyCall.PyObject}}:
 1  2  0  0
 0  0  1  3
 0  0  0  0

In [7]:
A.rref()[2] # 主成分のある列番号（Pythonの0始まりに注意）

(0, 2)

## 3.5節：連立1次方程式の解法

In [10]:
using SymPy
B = Sym[1 1 -2 1 0 0;
    3 2 -4 0 1 0; 
    2 2 -3 0 0 1]

3×6 Matrix{Sym}:
 1  1  -2  1  0  0
 3  2  -4  0  1  0
 2  2  -3  0  0  1

In [11]:
B.rref()[1]

3×6 Matrix{Sym{PyCall.PyObject}}:
 1  0  0  -2   1  0
 0  1  0  -1  -1  2
 0  0  1  -2   0  1

## 3.7節：Juliaで連立1次方程式の解き方

In [ ]:
A = [0 0 2; 1 0 1 ; 2 -1 1]
L, U = lu(A)

In [ ]:
A - L * U

In [ ]:
F = lu(A)

In [ ]:
F.P

In [ ]:
F.P * A - F.L * F.U

In [ ]:
L, U, p = lu(A)   
p

In [ ]:
b = [1; 2; 3]
x = U \ (L \ b[p])
# x = F \ b # これでもOK